Update versions + minor changes
ac-freeman/davis-EDI-rs pull request #21
Opened 2023-05-22 02:30 UTC by eric-unc

2023-05-22 12:52 UTC, ac-freeman requested changes

2023-05-22 12:52 UTC, ac-freeman commented on Cargo.toml
> +aedat = { git = "https://github.com/eric-unc/aedat-rs.git", version = "1.3.2"}
Don't use local references

2023-05-22 12:52 UTC, ac-freeman commented on src/util/reconstructor.rs
> +            #[cfg(target_family = "unix")]
Set up a GitHub Actions pipeline on your fork to test it for Linux & Windows before we merge. Use [this](https://github.com/ac-freeman/adder-codec-rs/blob/main/.github/workflows/rust_action_test_and_docs.yml) for inspiration.

2023-05-24 17:57 UTC, ac-freeman requested changes

2023-05-24 17:57 UTC, ac-freeman commented on .github/workflows/rust.yml
> +    runs-on: ubuntu-20.04
? You need to build for the whole matrix

2023-05-29 04:44 UTC, eric-unc commented
CI support is there for both Ubuntu Windows, inspired by a mix of adder-codec-rs's CI and opencv-rust's. It's on the messy side but it works. All that's left is to update the aedat reference once that's released.

2023-05-31 14:27 UTC, ac-freeman commented
Subsumed by #22

2023-05-31 14:27 UTC, closed without merging